######################################################################
# Automatically generated by qmake (2.01a) Wed 18. Jan 15:18:46 2012
######################################################################

TEMPLATE = lib

CONFIG(debug, debug|release) {
    TARGET = QHexViewd
} else {
    TARGET = QHexView
}

DESTDIR = $OUT_PWD/../../lib

DEFINES += QHEXVIEW_LIBRARY

DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QHexView.h QHexView_global.h
SOURCES += QHexView.cpp
